version: '3.9'

services:
  gate_state_machine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_LOC: /app
        STATE_MACHINE_TYPE: "Gate"
    environment:
      - NODE_NAME=GateStateMachine
      - STATE_MACHINE_TYPE=Gate
    ports:
      - "8080:8080"

  light_state_machine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_LOC: /app
        STATE_MACHINE_TYPE: "Light"
    environment:
      - NODE_NAME=LightStateMachine
      - STATE_MACHINE_TYPE=Light
    ports:
      - "8081:8080"

  controller_state_machine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_LOC: /app
        STATE_MACHINE_TYPE: "Controller"
    environment:
      - NODE_NAME=ControllerStateMachine
      - STATE_MACHINE_TYPE=Controller
    ports:
      - "8082:8080"
