services:
  gate-state-machine:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["--role=gate", "--port=8080"]
    ports:
      - "8080:8080"

  light-state-machine:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["--role=light", "--port=8080"]
    ports:
      - "8081:8080"

  controller-state-machine:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - gate-state-machine
      - light-state-machine
    command:
      [
        "--role=controller",
        "--port=8080",
        "--auto-simulate=true",
        "--sensor-sequence=seen,not_seen,seen,not_seen,seen,not_seen",
        "--simulation-delay-ms=250",
        "--peers=http://gate-state-machine:8080/event,http://light-state-machine:8080/event"
      ]
    ports:
      - "8082:8080"
